# This workflow tests that the dev container configuration within
# opensafely/research-template is correct with respect to the tests within
# `tests/dev_container.sh`. Notice that the dev container configuration lives in a
# different repository. This is because opensafely/research-template is a template
# repository; its contents are copied to multiple other repositories. Rather than test
# the dev container configuration in each of these multiple other repositories, we test
# it here, and assume that the copies don't deviate from the template repository. Doing
# so reduces the cost of updating the tests.
name: Test research template dev container

on:
  schedule:
    - cron: "18 8 * * *"
  workflow_dispatch:

jobs:
  dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout research-template repository
        uses: actions/checkout@v5
        with:
          repository: 'opensafely/research-template'

      - name: Checkout research-template-docker repository in subdirectory
        uses: actions/checkout@v5
        with:
          path: 'research-template/research-template-docker'

      - name: Test dev container
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          runCmd: ./research-template/research-template-docker/tests/dev_container.sh
